### PR TITLE
CSCFC4EMSCR-561 pull request to develop

### PR DESCRIPTION
**Pull request by masillan**
CSCFC4EMSCR-561 Clicking mapping source/target node only highlights one side of the schema trees: Changed clicking mapping source/target to highligt both source and target on crosswalk schema trees.

### CODE REVIEW

**Review by maariaw — APPROVED** [review]
Works beautifully in most cases. With a SHACL schema it didn't open parent nodes, but we might want to investigate that separately. Works with my CSV, JSON, XSD and SKOSRDF test schemas at least. SHACL I tested with https://mscr-test.2.rahtiapp.fi/schema/mscr:schema:6e832593-3800-4db7-856e-fadb50e7b4d6 (download button at the bottom of page)

**Comment by rquazi** [comment]
What is the status then, if we wanna investigate SHACL separately? should we then merge this PR to develop @maariaw

**Comment by maariaw** [comment]
If that's ok with @masillan ? You're not still working on this? Should I make a ticket for the SHACL fix if we merge this now?

**Comment by masillan** [comment]
CSCFC4EMSCR-599 have at least one fix for SHACL in case where mapped field is child of root element. Root element will appear as parent class of mapped field. There is now another pull request for CSCFC4EMSCR-599 open.

**Pull request merged**
